name: Pedido Catalogo API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Smoke Tests
        run: |
          newman run api-v1.0.postman_collection.json \
          -e HOM.postman_environment.json \
          --folder "Smoke" \
          --reporters cli

  validation:
    name: Validation Tests
    runs-on: ubuntu-latest
    needs: smoke

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Validation Tests
        run: |
          newman run api-v1.0.postman_collection.json \
          -e HOM.postman_environment.json \
          --folder "Validation" \
          --reporters cli

  business:
    name: Business Rule Tests
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Business Tests
        run: |
          newman run api-v1.0.postman_collection.json \
          -e HOM.postman_environment.json \
          --folder "Business" \
          --reporters cli